# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoViews_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoViews_iOS
  pod 'AGEVideoLayout', :path => '../../'
end

target 'VideoViews_Mac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoViews_Mac
  pod 'AGEVideoLayout', :path => '../../'
end
